version: '3'
services:
  # MySQL Service
  db:
    image: mysql:5.7.22
    container_name: oolora_mysql
    hostname: oolora_mysql
    ports:
      - "3306:3306"
    networks:
      services-network:
        aliases:
          - oolora_mysql_network
    environment:
      MYSQL_DATABASE: forge
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./dbdata:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf

  # PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: oolora
    environment:
      SERVICE_NAME: oolora
      SERVICE_TAGS: dev
    working_dir: /var/www/html/oolora
    links:
      - db:oolora_mysql
    networks:
      services-network:
        aliases:
          - oolora_app_network
    tty: true
    depends_on:
      - db
    ports:
      - "9000:9000"
    volumes:
       - ./:/var/www/html/oolora
       - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini

  # Nginx Service
#  webserver:
#    image: nginx:alpine
#    container_name: webserver
#    depends_on:
#      - app
#    ports:
#      - "8080:80"
#      - "8443:443"
#    volumes:
#      - ./:/var/www
#      - ./nginx/conf.d/:/etc/nginx/conf.d/



#Docker Networks
networks:
  services-network:
    name: services-network
    driver: bridge
